example.property: "I AM IN THE DEFAULT"
redis.server: "redis"
redis.port: "6379"
words: "boat,book,vote,seat"
spring:
        profiles: verbs
words: ran,knew,had,saw,bought
signing.key: "345345fsdfsf5345"
