example.property: "I AM IN THE DEFAULT"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
---
spring:
        profiles: subject
words: I,You,He,She,It

---
spring:
        profiles: verbs
words: ran,knew,had,saw,bought
